BOT_TOKEN               = "xoxb-xxxxxxxxxxxxxxxxxxxxxx or ssm://"
VERIFICATION_TOKEN      = "xxxxxxxxxxxxx or ssm://"
BOT_ID                  = "Uxxxxxx"
CHANNEL_ID              = "CXXXXXX"
GITHUB_USERNAME         = "xxxxx"
GITHUB_TOKEN            = "xxxxxxx or ssm://"
GITHUB_REPOSITORY_SLUG  = "xxxxxxxxx"
GIT_CLONE_LOCAL_PATH    = "/tmp/xxxxxxx"
GIT_COMMIT_AUTHOR_NAME  = "Kishikawa Katsumi"
GIT_COMMIT_AUTHOR_EMAIL = "kkishikawa@example.com"
INFOPLIST_PATH          = "REPO/info.plist"
GIT_BRANCHES            = "dev"